app = "travel-gold"
primary_region = "iad"

[build]
  builder = "docker"
  dockerfile = "./Dockerfile"
  ignorefile = ".dockerignore"

[env]
  NODE_ENV = "production"
  PORT = "3000"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [services.concurrency]
    hard_limit = 50
    soft_limit = 40
    type = "connections"

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    grace_period = "10s"
    interval = "10s"
    method = "GET"
    path = "/"
    protocol = "http"
    timeout = "5s"
    tls_skip_verify = false
