[variables]
NIXPACKS_NODE_VERSION = "20"
COREPACK_ENABLE_STRICT = "0"

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install -g pnpm@10.10.0 --force", "pnpm install --no-frozen-lockfile"]
